version: '3.9'

services:
  dev_db:
    image: postgres:15
    container_name: pilink_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pilink
      POSTGRES_PASSWORD: pilink
      POSTGRES_DB: pilink

  # api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     target: development
  #   command: npx prisma migrate dev && npx prisma generate && pnpm run start:dev
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - dev_db
  #   ports:
  #     - '3333:3333'
  #   volumes:
  #     - .:/usr/src/app
